server:
  port: 8088

logging:
  level:
    root: INFO

spring:
  profiles: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/betesda
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

mail:
  smtp:
    host: smtp.gmail.com
    port: 465
    username: [EMAIL_USERNAME]
    password: [EMAIL_PASSWORD]
    connectiontimeout: 60000
    timeout: 60000
    writetimeout: 60000

  properties:
    mail:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true

service:
  url: https://api.mailgun.net/v3/
  apikey: [API_KEY_MAILGUN]

application:
  domain:
    name: petrasistemas.com.br
  link:
    reset: http://localhost:8080/#/redefinir-senha/
